Make a proper way to clean state cookie
ueberauth/ueberauth pull request #139
Opened 2021-05-17 03:22 UTC by xinz

Hello,

In the https://github.com/ueberauth/ueberauth/pull/136 PR, we add a feature to protect CSRF attack by put the `state` parameter into cookie, and we remove the `state` cookie is after the `handle_callback!/1` function of the strategy in this changes, before this PR changes, in the `handle_callback!/1` function of the strategy we can do any proper process with Plug, but now we may see a similar "AlreadySentError" error if we make a redirection in the `handle_callback!/1`:

```
  1) test make ensure run_callback is after the internal state clean (UeberauthTest)
     test/ueberauth_test.exs:233
     ** (Plug.Conn.AlreadySentError) the response was already sent
     code: |> Ueberauth.run_callback(
     stacktrace:
       (plug 1.11.0) lib/plug/conn.ex:1720: Plug.Conn.update_cookies/2
       (ueberauth 0.6.3) lib/ueberauth/strategy.ex:370: Ueberauth.Strategy.run_handle_cleanup/2
       test/ueberauth_test.exs:251: (test)
```

In this PR, I change to put the `state` cookie clean before run `handle_callback!/1`, since the state parameter in cookie should be transparent for the strategy, and add a test case to catch this.

Please review and advise, cc @yordis @doomspork .

Thanks.

2021-05-17 04:01 UTC, doomspork requested changes
Thank you @xinz :tada: Just a few small change requests

2021-05-17 04:01 UTC, doomspork commented on test/ueberauth_test.exs
> +      |> Ueberauth.run_request(
```suggestion
      :get
      |> conn("/oauth/simple-provider/", id: "foo")
      |> Ueberauth.run_request(
```

2021-05-17 04:01 UTC, doomspork commented on test/ueberauth_test.exs
> +      |> Map.put(:cookies, conn.cookies)
```suggestion
    conn =
      :get
      |> conn("/oauth/simple-provider/callback", next_url: "http://localhost/fetch_user", id: "foo", code: code, state: state)
      |> Map.put(:cookies, conn.cookies)
```

2021-05-17 06:25 UTC, xinz commented on test/support/provider_with_csrf_attack_enabled.ex
> +    uri = %{uri | query: query} |> URI.to_string()
Thanks, done.

2021-05-17 06:28 UTC, xinz commented on test/support/provider_with_csrf_attack_enabled.ex
> +
Thanks, I have remove the mentioned L21, but I am not quite sure it is satisfied, please let know me if there are something still missing.

2021-05-17 06:29 UTC, xinz commented on test/ueberauth_test.exs
> +      |> Ueberauth.run_request(
Thanks, done.

2021-05-17 06:29 UTC, xinz commented on test/ueberauth_test.exs
> +      |> Map.put(:cookies, conn.cookies)
Thanks, done.

2021-05-17 06:30 UTC, xinz commented
Hi @doomspork, thanks for your suggestions, please review again when you have time for it.

2021-05-17 13:37 UTC, doomspork commented
Thank you @xinz! :purple_heart: 

@yordis do you want to take a quick peek at this before merging?

2021-05-17 14:58 UTC, xinz commented
Sorry that I accidentally re-click the send review request button if disturbed.

2021-06-04 16:09 UTC, yordis approved these changes

2021-06-11 18:42 UTC, merged