Fix route prefix (conn.script_name) in run/2
ueberauth/ueberauth pull request #147
Opened 2021-08-21 20:10 UTC by starkeepers

Closes #146 -

2021-08-22 00:45 UTC, yordis requested changes
Thank you so much for the PR,

Would you mind adding an entry here: https://github.com/ueberauth/ueberauth/blob/master/CHANGELOG.md

And add a unit test 🙏🏻

2021-08-22 09:22 UTC, starkeepers commented
I updated the changelog (assuming this goes into v0.8.0, since that version is not yet released on hex or on github releases). As for the test, I would love that, but I see no easy way to do it, from what I see in ueberauth_test.exs.

2021-09-16 18:38 UTC, yordis commented
THANK YOU so much @doomspork

I am gonna add the OWNERS file so I don't keep losing the notifications

2021-09-28 00:13 UTC, greg-rychlewski commented on lib/ueberauth.ex
> +    to_callback_path = Path.join(["/", route_prefix, options.callback_path])
```suggestion
    to_request_path  = Path.join([route_prefix, options.request_path])
    to_callback_path = Path.join([route_prefix, options.callback_path])
```
If `conn.script_name` is an empty list the previous method would return something like this `/./request_path`.

2021-09-28 00:13 UTC, greg-rychlewski commented on lib/ueberauth.ex
> +    to_callback_path = Path.join(["/", route_prefix, options.callback_path])
```suggestion
    to_request_path  = Path.join([route_prefix, options.request_path])
    to_callback_path = Path.join([route_prefix, options.callback_path])
```
If `conn.script_name` is an empty list the previous method would return something like this `/./request_path`.

2021-09-28 00:14 UTC, greg-rychlewski commented
@starkeepers  You can add a test for these like this

```elixir
  test "request phase: correct paths created for multiple segment script_name" do
    conn = %{conn(:get, "/auth/simple") | script_name: ["a", "b"]} |> SpecRouter.call(@opts)

    assert Helpers.request_path(conn) == "/a/b/auth/simple"
    assert Helpers.callback_path(conn) == "/a/b/auth/simple/callback"
  end

  test "callback phase: correct paths created for multiple segment script_name" do
    conn =
      %{conn(:get, "/auth/simple/callback") | script_name: ["a", "b"]}
      |> SpecRouter.call(@opts)

    assert Helpers.request_path(conn) == "/a/b/auth/simple"
    assert Helpers.callback_path(conn) == "/a/b/auth/simple/callback"
  end
```

2022-07-05 23:40 UTC, yordis commented
close in favor of #166

2022-07-05 23:40 UTC, closed without merging