Prefer `x-forwarded-host` to construct callback_url
ueberauth/ueberauth pull request #161
Opened 2022-04-26 18:38 UTC by jerodsanto

This feature is similar to PR #14 that added support for differing port for apps behind proxies. 

We recently moved [our app](https://github.com/thechangelog/changelog.com) from Linode to Fly, which broke Ueberauth because the callback URL that gets generated uses the Fly app domain instead of our public [changelog.com](https://changelog.com) domain.

I have deployed and tested this change in production and confirmed it fixes the issue for us and you can sign in/up via Twitter and GitHub once again.

2022-04-27 14:48 UTC, yordis requested changes
Thank you so much for the contribution,

Do you mind updating the `CHANGELOG.md` and bump the version of the package following SemVer?

2022-05-16 14:58 UTC, jerodsanto commented
@yordis bumping this in case you missed it! 

I updated the version and changelog so it should be good to go! 💚

2022-05-16 18:33 UTC, yordis approved these changes

2022-05-16 20:52 UTC, merged

2022-05-16 20:52 UTC, yordis commented
🚀