Add option for state param cookie SameSite
ueberauth/ueberauth pull request #164
Opened 2022-06-14 11:55 UTC by langalex

This PR adds a strategy option to change the SameSite value of the state param cookie.

Changing the same_site is required in certain scenarios like doing OAuth in an iframe.

see https://github.com/ueberauth/ueberauth/issues/148

2022-06-15 22:15 UTC, yordis commented
@langalex I am guessing we also need to fix `ueberauth_apple` now or is it depend on the end-user setup?

2022-06-15 22:15 UTC, yordis approved these changes

2022-06-16 09:33 UTC, langalex commented
@yordis it might be useful for some people to be able to change SameSite for Apple as well but I think it's a bit of an edge case, i.e. does not need to happen now.

2022-06-16 19:58 UTC, yordis requested changes

2022-06-17 17:03 UTC, yordis approved these changes

2022-06-17 17:08 UTC, merged

2022-06-18 16:30 UTC, langalex commented
@yordis thanks for the help. can you push the new version to hex?